language: common-lisp

env:
  matrix:
    - LISP=allego
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=ecl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - cl -e '(in-package :cl-user)'
       -e "(ql:quickload '(prove let-over-lambda))"
       -e '(setf prove:*debug-on-error* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(or (prove:run :let-over-lambda-test)
               (uiop:quit -1))'
